### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by Peletic** [wkenny80/sunset-app-apcs#1]
- [ ] find suitable api
- [ ] create decent "good sunset" alg using said api
- [ ] frontend go brrr
- [ ] also shadcn and some other stuff
